[package]
name = "mhw-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.9", features = ["derive"] }
fs_extra = "1.3.0"
serde = { version = "1.0.204", features = ["derive"] }
vipera = "0.1.2"
